/*
DIALOGUE_DEFINITIONS.H

header included in hcex build.
*/

#ifndef __DIALOGUE_DEFINITIONS_H
#define __DIALOGUE_DEFINITIONS_H
#pragma once

/* ---------- constants */

enum
{
	_unit_speech_none = 0,
	_unit_speech_idle,
	_unit_speech_pain,
	_unit_speech_talk,
	_unit_speech_communicate,
	_unit_speech_shout,
	_unit_speech_scripted,
	_unit_speech_involuntary,
	_unit_speech_exclamation,
	_unit_speech_scream,
	_unit_speech_death,
	NUMBER_OF_UNIT_SPEECH_PRIORITIES,
};

enum
{
	_vocalization_idle_noncombat = 0,
	_vocalization_idle_combat,
	_vocalization_idle_flee,
	_vocalization_idle_unused2,
	_vocalization_idle_unused3,
	_vocalization_idle_unused4,
	_vocalization_pain_body,
	_vocalization_pain_body_major,
	_vocalization_pain_shield,
	_vocalization_pain_falling,
	_vocalization_scream_fear,
	_vocalization_scream_pain,
	_vocalization_maimed_limb,
	_vocalization_maimed_head,
	_vocalization_death_quiet,
	_vocalization_death_violent,
	_vocalization_death_falling,
	_vocalization_death_agonizing,
	_vocalization_death_instant,
	_vocalization_death_flying,
	_vocalization_involuntary_unused1,
	_vocalization_shot_friend,
	_vocalization_shot_friend_player,
	_vocalization_shot_enemy,
	_vocalization_shot_enemy_comment,
	_vocalization_hurtingpeople_unused1,
	_vocalization_hurtingpeople_unused2,
	_vocalization_hurtingpeople_unused3,
	_vocalization_hurtingpeople_unused4,
	_vocalization_hurt_friend,
	_vocalization_hurt_friend_reply,
	_vocalization_hurt_friend_player,
	_vocalization_hurt_enemy,
	_vocalization_hurt_enemy_reply,
	_vocalization_hurt_enemy_comment,
	_vocalization_hurt_enemy_bullet,
	_vocalization_hurt_enemy_needler,
	_vocalization_hurt_enemy_plasma,
	_vocalization_hurt_enemy_sniper,
	_vocalization_hurt_enemy_grenade,
	_vocalization_hurt_enemy_explosion,
	_vocalization_hurt_enemy_melee,
	_vocalization_hurt_enemy_flame,
	_vocalization_hurt_enemy_shotgun,
	_vocalization_hurt_enemy_vehicle,
	_vocalization_hurt_enemy_mountedweapon,
	_vocalization_hurt_unused1,
	_vocalization_hurt_unused2,
	_vocalization_hurt_unused3,
	_vocalization_killed_friend,
	_vocalization_killed_friend_comment,
	_vocalization_killed_friend_player,
	_vocalization_killed_friend_player_comment,
	_vocalization_killed_enemy,
	_vocalization_killed_enemy_comment,
	_vocalization_killed_enemy_player,
	_vocalization_killed_enemy_player_comment,
	_vocalization_killed_enemy_covenant,
	_vocalization_killed_enemy_covenant_comment,
	_vocalization_killed_enemy_floodcombat,
	_vocalization_killed_enemy_floodcombat_comment,
	_vocalization_killed_enemy_floodcarrier,
	_vocalization_killed_enemy_floodcarrier_comment,
	_vocalization_killed_enemy_sentinel,
	_vocalization_killed_enemy_sentinel_comment,
	_vocalization_killed_enemy_bullet,
	_vocalization_killed_enemy_needler,
	_vocalization_killed_enemy_plasma,
	_vocalization_killed_enemy_sniper,
	_vocalization_killed_enemy_grenade,
	_vocalization_killed_enemy_explosion,
	_vocalization_killed_enemy_melee,
	_vocalization_killed_enemy_flame,
	_vocalization_killed_enemy_shotgun,
	_vocalization_killed_enemy_vehicle,
	_vocalization_killed_enemy_mountedweapon,
	_vocalization_killing_spree,
	_vocalization_killingpeople_unused1,
	_vocalization_killingpeople_unused2,
	_vocalization_killingpeople_unused3,
	_vocalization_player_kill_comment,
	_vocalization_player_kill_bullet_comment,
	_vocalization_player_kill_needler_comment,
	_vocalization_player_kill_plasma_comment,
	_vocalization_player_kill_sniper_comment,
	_vocalization_player_kill_grenade_comment,
	_vocalization_player_kill_explosion_comment,
	_vocalization_player_kill_melee_comment,
	_vocalization_player_kill_flame_comment,
	_vocalization_player_kill_shotgun_comment,
	_vocalization_player_kill_vehicle_comment,
	_vocalization_player_kill_mountedweapon_comment,
	_vocalization_player_killing_spree_comment,
	_vocalization_playerkill_unused1,
	_vocalization_playerkill_unused2,
	_vocalization_playerkill_unused3,
	_vocalization_friend_died,
	_vocalization_friend_player_died,
	_vocalization_friend_killed_by_friend,
	_vocalization_friend_killed_by_friend_player,
	_vocalization_friend_killed_by_enemy,
	_vocalization_friend_killed_by_enemy_player,
	_vocalization_friend_killed_by_covenant,
	_vocalization_friend_killed_by_flood,
	_vocalization_friend_killed_by_sentinel,
	_vocalization_friend_betrayed,
	_vocalization_friendsdying_unused1,
	_vocalization_friendsdying_unused2,
	_vocalization_sighted_enemy_new,
	_vocalization_sighted_enemy_recent,
	_vocalization_sighted_enemy_searching,
	_vocalization_unexpected_enemy,
	_vocalization_dead_friend_found,
	_vocalization_allegiance_broken,
	_vocalization_allegiance_reformed,
	_vocalization_grenade_throwing,
	_vocalization_grenade_startle,
	_vocalization_grenade_sighted,
	_vocalization_grenade_danger_enemy,
	_vocalization_grenade_danger_self,
	_vocalization_grenade_danger_friend,
	_vocalization_shouting_unused1,
	_vocalization_shouting_unused2,
	_vocalization_sighted_enemy_near_reply,
	_vocalization_sighted_enemy_far_reply,
	_vocalization_alert_noncombat,
	_vocalization_alert_noncombat_reply,
	_vocalization_alert_lost_contact,
	_vocalization_alert_lost_contact_reply,
	_vocalization_blocked,
	_vocalization_blocked_reply,
	_vocalization_search_start,
	_vocalization_search_query,
	_vocalization_search_query_reply,
	_vocalization_search_report,
	_vocalization_search_abandon,
	_vocalization_search_group_abandon,
	_vocalization_uncover_start,
	_vocalization_uncover_start_reply,
	_vocalization_advance,
	_vocalization_advance_reply,
	_vocalization_retreat,
	_vocalization_retreat_reply,
	_vocalization_cover,
	_vocalization_group_unused1,
	_vocalization_group_unused2,
	_vocalization_group_unused3,
	_vocalization_group_unused4,
	_vocalization_sighted_friend_player,
	_vocalization_shooting,
	_vocalization_shooting_vehicle,
	_vocalization_shooting_berserk,
	_vocalization_shooting_group,
	_vocalization_shooting_traitor,
	_vocalization_taunt,
	_vocalization_taunt_reply,
	_vocalization_flee,
	_vocalization_flee_reply,
	_vocalization_flee_leader_died,
	_vocalization_attempted_flee,
	_vocalization_attempted_flee_reply,
	_vocalization_lost_contact,
	_vocalization_hiding_finished,
	_vocalization_vehicle_entry,
	_vocalization_vehicle_exit,
	_vocalization_vehicle_woohoo,
	_vocalization_vehicle_scared,
	_vocalization_vehicle_collision,
	_vocalization_partially_sighted,
	_vocalization_nothing_there,
	_vocalization_pleading,
	_vocalization_actions_unused1,
	_vocalization_actions_unused2,
	_vocalization_actions_unused3,
	_vocalization_actions_unused4,
	_vocalization_actions_unused5,
	_vocalization_actions_unused6,
	_vocalization_surprise,
	_vocalization_berserk,
	_vocalization_melee,
	_vocalization_dive,
	_vocalization_uncover_exclamation,
	_vocalization_leap,
	_vocalization_resurrect,
	_vocalization_exclamation_unused1,
	_vocalization_exclamation_unused2,
	_vocalization_exclamation_unused3,
	_vocalization_exclamation_unused4,
	_vocalization_celebrate,
	_vocalization_check_body_enemy,
	_vocalization_check_body_friend,
	_vocalization_shoot_corpse,
	_vocalization_shoot_corpse_player,
	_vocalization_postcombataction_unused1,
	_vocalization_postcombataction_unused2,
	_vocalization_postcombataction_unused3,
	_vocalization_postcombataction_unused4,
	_vocalization_postcombat_alone,
	_vocalization_postcombat_unscathed,
	_vocalization_postcombat_wounded,
	_vocalization_postcombat_wounded_reply,
	_vocalization_postcombat_massacre,
	_vocalization_postcombat_massacre_reply,
	_vocalization_postcombat_triumph,
	_vocalization_postcombat_triumph_reply,
	_vocalization_postcombatchatter_unused1,
	_vocalization_postcombatchatter_unused2,
	_vocalization_postcombatchatter_unused3,
	_vocalization_postcombatchatter_unused4,
	NUMBER_OF_VOCALIZATION_TYPES,
	MAXIMUM_NUMBER_OF_VOCALIZATION_TYPES = 256,
};

/* ---------- macros */

/* ---------- structures */

/* ---------- prototypes/EXAMPLE.C */

short dialogue_get_vocalization_type_by_name(char const *name);
char const *dialogue_get_vocalization_name(short vocalization_type, boolean unknown);

/* ---------- globals */

/* ---------- public code */

#endif // __DIALOGUE_DEFINITIONS_H
