#!/usr/bin/env python3

import sys
from pathlib import Path

HEADER = (
    "/*\n"
    "SOUND_DSOUND_XBOX_EFFECTS_IMAGE.H\n"
    "do not edit this file; it is machine-generated.\n"
    "*/\n"
    "\n"
    "static const byte dsound_effects_image[]= {"
)

# dsound_effects_image in cachebeta.exe
DSP_IMAGE_FILE_OFFSET = 0x2AB2A8
DSP_IMAGE_SIZE = 0x3A5C

def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <baserom> <output>")
    baserom = Path(sys.argv[1])
    output = Path(sys.argv[2])

    with open(baserom, "rb") as f:
        f.seek(DSP_IMAGE_FILE_OFFSET)
        data = f.read(DSP_IMAGE_SIZE)
    if len(data) != DSP_IMAGE_SIZE:
        sys.exit(f"{baserom}: couldn't read the DSP image")

    text = HEADER
    for i, b in enumerate(data):
        if i % 8 == 0:
            text += "\n\t"
        text += f"0x{b:x}, "
    text += "\n};\n"

    # Only rewrite when the contents change
    if output.is_file() and output.read_text(encoding="utf-8") == text:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")

if __name__ == "__main__":
    main()
